/*
 * Copyright 2018 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#if (MODEL_SPT == MODEL_CTSK_N650_V100)
#if 1
#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0xCF30C000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x45FF000EU /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_B1_13 (coord D14), WDOG_B */
/* Routed pin properties */
#define BOARD_INITPINS_WDOG_B_PERIPHERAL                                   WDOG1   /*!< Peripheral name */
#define BOARD_INITPINS_WDOG_B_SIGNAL                                      wdog_b   /*!< Signal name */

/* GPIO_AD_B1_06 (coord J12), [J12] GPIO_AD_B1_06_ADC1 */
/* Routed pin properties */
#define BOARD_INITPINS_ADC1_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC1_SIGNAL                                            IN   /*!< Signal name */
#define BOARD_INITPINS_ADC1_CHANNEL                                          11U   /*!< Signal channel */

/* GPIO_AD_B1_07 (coord K10), [K10] GPIO_AD_B1_07_ADC2 */
/* Routed pin properties */
#define BOARD_INITPINS_ADC2_PERIPHERAL                                      ADC2   /*!< Peripheral name */
#define BOARD_INITPINS_ADC2_SIGNAL                                            IN   /*!< Signal name */
#define BOARD_INITPINS_ADC2_CHANNEL                                          12U   /*!< Signal channel */

/* GPIO_AD_B0_14 (coord H14), MCU_PD_TEST_TRIGGER */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_PD_TEST_TRIGGER_PERIPHERAL                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_PD_TEST_TRIGGER_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_PD_TEST_TRIGGER_CHANNEL                           14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_PD_TEST_TRIGGER_GPIO                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_PD_TEST_TRIGGER_GPIO_PIN                          14U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_PD_TEST_TRIGGER_GPIO_PIN_MASK             (1U << 14U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_PD_TEST_TRIGGER_PORT                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_PD_TEST_TRIGGER_PIN                               14U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_PD_TEST_TRIGGER_PIN_MASK                  (1U << 14U)   /*!< PORT pin mask */

/* GPIO_AD_B0_15 (coord L10), MCU_LED_TEST_TRIGGER */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_LED_TEST_TRIGGER_PERIPHERAL                     GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_LED_TEST_TRIGGER_SIGNAL                       gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_LED_TEST_TRIGGER_CHANNEL                          15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_LED_TEST_TRIGGER_GPIO                           GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_TEST_TRIGGER_GPIO_PIN                         15U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_LED_TEST_TRIGGER_GPIO_PIN_MASK            (1U << 15U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_LED_TEST_TRIGGER_PORT                           GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_TEST_TRIGGER_PIN                              15U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_LED_TEST_TRIGGER_PIN_MASK                 (1U << 15U)   /*!< PORT pin mask */

/* GPIO_AD_B1_08 (coord H13), ADC_MUX11 */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_MUX11_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_MUX11_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADC_MUX11_CHANNEL                                     19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADC_MUX11_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADC_MUX11_GPIO_PIN                                    19U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADC_MUX11_GPIO_PIN_MASK                       (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ADC_MUX11_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_MUX11_PIN                                         19U   /*!< PORT pin number */
#define BOARD_INITPINS_ADC_MUX11_PIN_MASK                            (1U << 19U)   /*!< PORT pin mask */

/* GPIO_AD_B1_04 (coord L12), ADD_MUX12 */
/* Routed pin properties */
#define BOARD_INITPINS_ADD_MUX12_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ADD_MUX12_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADD_MUX12_CHANNEL                                     20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADD_MUX12_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX12_GPIO_PIN                                    20U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADD_MUX12_GPIO_PIN_MASK                       (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ADD_MUX12_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX12_PIN                                         20U   /*!< PORT pin number */
#define BOARD_INITPINS_ADD_MUX12_PIN_MASK                            (1U << 20U)   /*!< PORT pin mask */

/* GPIO_AD_B1_05 (coord K12), ADD_MUX13 */
/* Routed pin properties */
#define BOARD_INITPINS_ADD_MUX13_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ADD_MUX13_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADD_MUX13_CHANNEL                                     21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADD_MUX13_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX13_GPIO_PIN                                    21U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADD_MUX13_GPIO_PIN_MASK                       (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ADD_MUX13_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX13_PIN                                         21U   /*!< PORT pin number */
#define BOARD_INITPINS_ADD_MUX13_PIN_MASK                            (1U << 21U)   /*!< PORT pin mask */



/* GPIO_AD_B1_09 (coord M13), TEST_POING_2 */
/* Routed pin properties */
#define BOARD_INITPINS_TEST_POING_2_PERIPHERAL                             GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_TEST_POING_2_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITPINS_TEST_POING_2_CHANNEL                                  25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TEST_POING_2_GPIO                                   GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_TEST_POING_2_GPIO_PIN                                 25U   /*!< GPIO pin number */
#define BOARD_INITPINS_TEST_POING_2_GPIO_PIN_MASK                    (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_TEST_POING_2_PORT                                   GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_TEST_POING_2_PIN                                      25U   /*!< PORT pin number */
#define BOARD_INITPINS_TEST_POING_2_PIN_MASK                         (1U << 25U)   /*!< PORT pin mask */

/* GPIO_AD_B1_10 (coord L13), TEST_POING_3 */
/* Routed pin properties */
#define BOARD_INITPINS_TEST_POING_3_PERIPHERAL                             GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_TEST_POING_3_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITPINS_TEST_POING_3_CHANNEL                                  26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_TEST_POING_3_GPIO                                   GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_TEST_POING_3_GPIO_PIN                                 26U   /*!< GPIO pin number */
#define BOARD_INITPINS_TEST_POING_3_GPIO_PIN_MASK                    (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_TEST_POING_3_PORT                                   GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_TEST_POING_3_PIN                                      26U   /*!< PORT pin number */
#define BOARD_INITPINS_TEST_POING_3_PIN_MASK                         (1U << 26U)   /*!< PORT pin mask */

/* GPIO_AD_B1_11 (coord J13), MCU_LED_HGROUP_DATA */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_LED_HGROUP_DATA_PERIPHERAL                      GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_LED_HGROUP_DATA_SIGNAL                        gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_LED_HGROUP_DATA_CHANNEL                           27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_LED_HGROUP_DATA_GPIO                            GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_HGROUP_DATA_GPIO_PIN                          27U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_LED_HGROUP_DATA_GPIO_PIN_MASK             (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_LED_HGROUP_DATA_PORT                            GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_HGROUP_DATA_PIN                               27U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_LED_HGROUP_DATA_PIN_MASK                  (1U << 27U)   /*!< PORT pin mask */

/* GPIO_AD_B1_14 (coord G12), MCU_ADC_GROUP_SELECT_0 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_0_PERIPHERAL                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_0_SIGNAL                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_0_CHANNEL                        30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_0_GPIO                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_0_GPIO_PIN                       30U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_0_GPIO_PIN_MASK          (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_0_PORT                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_0_PIN                            30U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_0_PIN_MASK               (1U << 30U)   /*!< PORT pin mask */

/* GPIO_AD_B1_15 (coord J14), MCU_ADC_GROUP_SELECT_1 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_1_PERIPHERAL                   GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_1_SIGNAL                     gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_1_CHANNEL                        31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_1_GPIO                         GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_1_GPIO_PIN                       31U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_1_GPIO_PIN_MASK          (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_1_PORT                         GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_1_PIN                            31U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_ADC_GROUP_SELECT_1_PIN_MASK               (1U << 31U)   /*!< PORT pin mask */

/* GPIO_B0_01 (coord E7), MCU_LED_CELL_CTRL1 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL1_PERIPHERAL                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL1_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL1_CHANNEL                             1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL1_GPIO                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL1_GPIO_PIN                            1U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL1_GPIO_PIN_MASK               (1U << 1U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL1_PORT                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL1_PIN                                 1U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL1_PIN_MASK                    (1U << 1U)   /*!< PORT pin mask */

/* GPIO_B0_02 (coord E8), MCU_LED_CELL_CTRL2 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL2_PERIPHERAL                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL2_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL2_CHANNEL                             2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL2_GPIO                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL2_GPIO_PIN                            2U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL2_GPIO_PIN_MASK               (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL2_PORT                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL2_PIN                                 2U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL2_PIN_MASK                    (1U << 2U)   /*!< PORT pin mask */

/* GPIO_B0_03 (coord D8), MCU_LED_CELL_CTRL3 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL3_PERIPHERAL                       GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL3_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL3_CHANNEL                             3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL3_GPIO                             GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL3_GPIO_PIN                            3U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL3_GPIO_PIN_MASK               (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL3_PORT                             GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL3_PIN                                 3U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_LED_CELL_CTRL3_PIN_MASK                    (1U << 3U)   /*!< PORT pin mask */

/* GPIO_B1_00 (coord A11), MCU_SINK_DAC_0 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SINK_DAC_0_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SINK_DAC_0_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SINK_DAC_0_CHANNEL                                16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SINK_DAC_0_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_0_GPIO_PIN                               16U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_0_GPIO_PIN_MASK                  (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SINK_DAC_0_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_0_PIN                                    16U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_0_PIN_MASK                       (1U << 16U)   /*!< PORT pin mask */

/* GPIO_B1_01 (coord B11), MCU_SINK_DAC_1 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SINK_DAC_1_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SINK_DAC_1_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SINK_DAC_1_CHANNEL                                17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SINK_DAC_1_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_1_GPIO_PIN                               17U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_1_GPIO_PIN_MASK                  (1U << 17U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SINK_DAC_1_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_1_PIN                                    17U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_1_PIN_MASK                       (1U << 17U)   /*!< PORT pin mask */

/* GPIO_B1_02 (coord C11), MCU_SINK_DAC_2 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SINK_DAC_2_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SINK_DAC_2_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SINK_DAC_2_CHANNEL                                18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SINK_DAC_2_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_2_GPIO_PIN                               18U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_2_GPIO_PIN_MASK                  (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SINK_DAC_2_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_2_PIN                                    18U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_2_PIN_MASK                       (1U << 18U)   /*!< PORT pin mask */

/* GPIO_B1_03 (coord D11), MCU_SINK_DAC_3 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SINK_DAC_3_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SINK_DAC_3_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SINK_DAC_3_CHANNEL                                19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SINK_DAC_3_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_3_GPIO_PIN                               19U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_3_GPIO_PIN_MASK                  (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SINK_DAC_3_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_3_PIN                                    19U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_3_PIN_MASK                       (1U << 19U)   /*!< PORT pin mask */

/* GPIO_B1_04 (coord E12), MCU_SINK_DAC_4 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SINK_DAC_4_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SINK_DAC_4_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SINK_DAC_4_CHANNEL                                20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SINK_DAC_4_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_4_GPIO_PIN                               20U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_4_GPIO_PIN_MASK                  (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SINK_DAC_4_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_4_PIN                                    20U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_4_PIN_MASK                       (1U << 20U)   /*!< PORT pin mask */

/* GPIO_B1_05 (coord D12), MCU_SINK_DAC_5 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SINK_DAC_5_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SINK_DAC_5_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SINK_DAC_5_CHANNEL                                21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SINK_DAC_5_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_5_GPIO_PIN                               21U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_5_GPIO_PIN_MASK                  (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SINK_DAC_5_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_5_PIN                                    21U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_5_PIN_MASK                       (1U << 21U)   /*!< PORT pin mask */

/* GPIO_B1_06 (coord C12), MCU_SINK_DAC_6 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SINK_DAC_6_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SINK_DAC_6_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SINK_DAC_6_CHANNEL                                22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SINK_DAC_6_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_6_GPIO_PIN                               22U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_6_GPIO_PIN_MASK                  (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SINK_DAC_6_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_6_PIN                                    22U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_6_PIN_MASK                       (1U << 22U)   /*!< PORT pin mask */

/* GPIO_B1_07 (coord B12), MCU_SINK_DAC_7 */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_SINK_DAC_7_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_SINK_DAC_7_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_SINK_DAC_7_CHANNEL                                23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_SINK_DAC_7_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_7_GPIO_PIN                               23U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_7_GPIO_PIN_MASK                  (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_SINK_DAC_7_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_SINK_DAC_7_PIN                                    23U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_SINK_DAC_7_PIN_MASK                       (1U << 23U)   /*!< PORT pin mask */

/* GPIO_B1_08 (coord A12), MCU_PD_SHIFT_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_PD_SHIFT_CLK_PERIPHERAL                         GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_PD_SHIFT_CLK_SIGNAL                           gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_PD_SHIFT_CLK_CHANNEL                              24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_PD_SHIFT_CLK_GPIO                               GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_PD_SHIFT_CLK_GPIO_PIN                             24U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_PD_SHIFT_CLK_GPIO_PIN_MASK                (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_PD_SHIFT_CLK_PORT                               GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_PD_SHIFT_CLK_PIN                                  24U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_PD_SHIFT_CLK_PIN_MASK                     (1U << 24U)   /*!< PORT pin mask */

/* GPIO_B1_10 (coord B13), MCU_LED_GROUP_EN */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_LED_GROUP_EN_PERIPHERAL                         GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_LED_GROUP_EN_SIGNAL                           gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_LED_GROUP_EN_CHANNEL                              26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_LED_GROUP_EN_GPIO                               GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_GROUP_EN_GPIO_PIN                             26U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_LED_GROUP_EN_GPIO_PIN_MASK                (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_LED_GROUP_EN_PORT                               GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_LED_GROUP_EN_PIN                                  26U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_LED_GROUP_EN_PIN_MASK                     (1U << 26U)   /*!< PORT pin mask */

/* GPIO_B1_14 (coord C14), MCU_PD_SHIFT_DATA */
/* Routed pin properties */
#define BOARD_INITPINS_MCU_PD_SHIFT_DATA_PERIPHERAL                        GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_MCU_PD_SHIFT_DATA_SIGNAL                          gpio_io   /*!< Signal name */
#define BOARD_INITPINS_MCU_PD_SHIFT_DATA_CHANNEL                             30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_MCU_PD_SHIFT_DATA_GPIO                              GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_MCU_PD_SHIFT_DATA_GPIO_PIN                            30U   /*!< GPIO pin number */
#define BOARD_INITPINS_MCU_PD_SHIFT_DATA_GPIO_PIN_MASK               (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_MCU_PD_SHIFT_DATA_PORT                              GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_MCU_PD_SHIFT_DATA_PIN                                 30U   /*!< PORT pin number */
#define BOARD_INITPINS_MCU_PD_SHIFT_DATA_PIN_MASK                    (1U << 30U)   /*!< PORT pin mask */

#else
#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0xC839C000U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x4FFF0007U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_B1_13 (coord D14), WDOG_B */
/* Routed pin properties */
#define BOARD_INITPINS_WDOG_B_PERIPHERAL                                   WDOG1   /*!< Peripheral name */
#define BOARD_INITPINS_WDOG_B_SIGNAL                                      wdog_b   /*!< Signal name */

/* GPIO_AD_B1_06 (coord J12), [J12] GPIO_AD_B1_06_ADC1 */
/* Routed pin properties */
#define BOARD_INITPINS_ADC1_PERIPHERAL                                      ADC1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC1_SIGNAL                                            IN   /*!< Signal name */
#define BOARD_INITPINS_ADC1_CHANNEL                                          11U   /*!< Signal channel */

/* GPIO_AD_B1_07 (coord K10), [K10] GPIO_AD_B1_07_ADC2 */
/* Routed pin properties */
#define BOARD_INITPINS_ADC2_PERIPHERAL                                      ADC2   /*!< Peripheral name */
#define BOARD_INITPINS_ADC2_SIGNAL                                            IN   /*!< Signal name */
#define BOARD_INITPINS_ADC2_CHANNEL                                          12U   /*!< Signal channel */

/* GPIO_AD_B0_14 (coord H14), MCU_PD_TEST_TRIGGER */
/* Routed pin properties */
#define BOARD_INITPINS_DEBUG_TP1_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_DEBUG_TP1_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DEBUG_TP1_CHANNEL                                     14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DEBUG_TP1_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DEBUG_TP1_GPIO_PIN                                    14U   /*!< GPIO pin number */
#define BOARD_INITPINS_DEBUG_TP1_GPIO_PIN_MASK                       (1U << 14U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DEBUG_TP1_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_TP1_PIN                                         14U   /*!< PORT pin number */
#define BOARD_INITPINS_DEBUG_TP1_PIN_MASK                            (1U << 14U)   /*!< PORT pin mask */

/* GPIO_AD_B0_15 (coord L10), MCU_LED_TEST_TRIGGER */
/* Routed pin properties */
#define BOARD_INITPINS_DEBUG_TP2_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_DEBUG_TP2_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_DEBUG_TP2_CHANNEL                                     15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DEBUG_TP2_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_DEBUG_TP2_GPIO_PIN                                    15U   /*!< GPIO pin number */
#define BOARD_INITPINS_DEBUG_TP2_GPIO_PIN_MASK                       (1U << 15U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_DEBUG_TP2_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_TP2_PIN                                         15U   /*!< PORT pin number */
#define BOARD_INITPINS_DEBUG_TP2_PIN_MASK                            (1U << 15U)   /*!< PORT pin mask */

/* GPIO_AD_B1_00 (coord J11), MCU_AN_SW_EN1 */
/* Routed pin properties */
#define BOARD_INITPINS_AN_SW_EN1_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_AN_SW_EN1_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_AN_SW_EN1_CHANNEL                                     16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_AN_SW_EN1_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_AN_SW_EN1_GPIO_PIN                                    16U   /*!< GPIO pin number */
#define BOARD_INITPINS_AN_SW_EN1_GPIO_PIN_MASK                       (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_AN_SW_EN1_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_AN_SW_EN1_PIN                                         16U   /*!< PORT pin number */
#define BOARD_INITPINS_AN_SW_EN1_PIN_MASK                            (1U << 16U)   /*!< PORT pin mask */

/* GPIO_AD_B1_03 (coord M12), ADD_MUX11 */
/* Routed pin properties */
#define BOARD_INITPINS_ADD_MUX11_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ADD_MUX11_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADD_MUX11_CHANNEL                                     19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADD_MUX11_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX11_GPIO_PIN                                    19U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADD_MUX11_GPIO_PIN_MASK                       (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ADD_MUX11_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX11_PIN                                         19U   /*!< PORT pin number */
#define BOARD_INITPINS_ADD_MUX11_PIN_MASK                            (1U << 19U)   /*!< PORT pin mask */

/* GPIO_AD_B1_04 (coord L12), ADD_MUX12 */
/* Routed pin properties */
#define BOARD_INITPINS_ADD_MUX12_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ADD_MUX12_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADD_MUX12_CHANNEL                                     20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADD_MUX12_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX12_GPIO_PIN                                    20U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADD_MUX12_GPIO_PIN_MASK                       (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ADD_MUX12_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX12_PIN                                         20U   /*!< PORT pin number */
#define BOARD_INITPINS_ADD_MUX12_PIN_MASK                            (1U << 20U)   /*!< PORT pin mask */

/* GPIO_AD_B1_05 (coord K12), ADD_MUX13 */
/* Routed pin properties */
#define BOARD_INITPINS_ADD_MUX13_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ADD_MUX13_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADD_MUX13_CHANNEL                                     21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADD_MUX13_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX13_GPIO_PIN                                    21U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADD_MUX13_GPIO_PIN_MASK                       (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ADD_MUX13_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ADD_MUX13_PIN                                         21U   /*!< PORT pin number */
#define BOARD_INITPINS_ADD_MUX13_PIN_MASK                            (1U << 21U)   /*!< PORT pin mask */

/* GPIO_AD_B1_11 (coord J13), MCU_LED_HGROUP_DATA */
/* Routed pin properties */
#define BOARD_INITPINS_LED_HGROUP_DATA_PERIPHERAL                          GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_LED_HGROUP_DATA_SIGNAL                            gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_HGROUP_DATA_CHANNEL                               27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_HGROUP_DATA_GPIO                                GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_HGROUP_DATA_GPIO_PIN                              27U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_HGROUP_DATA_GPIO_PIN_MASK                 (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_HGROUP_DATA_PORT                                GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_HGROUP_DATA_PIN                                   27U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_HGROUP_DATA_PIN_MASK                      (1U << 27U)   /*!< PORT pin mask */

/* GPIO_AD_B1_14 (coord G12), MCU_ADC_GROUP_SELECT_0 */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_GROUP_SELECT_0_PERIPHERAL                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_GROUP_SELECT_0_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADC_GROUP_SELECT_0_CHANNEL                            30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADC_GROUP_SELECT_0_GPIO                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADC_GROUP_SELECT_0_GPIO_PIN                           30U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADC_GROUP_SELECT_0_GPIO_PIN_MASK              (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ADC_GROUP_SELECT_0_PORT                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_GROUP_SELECT_0_PIN                                30U   /*!< PORT pin number */
#define BOARD_INITPINS_ADC_GROUP_SELECT_0_PIN_MASK                   (1U << 30U)   /*!< PORT pin mask */

/* GPIO_AD_B1_15 (coord J14), MCU_ADC_GROUP_SELECT_1 */
/* Routed pin properties */
#define BOARD_INITPINS_ADC_GROUP_SELECT_1_PERIPHERAL                       GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_ADC_GROUP_SELECT_1_SIGNAL                         gpio_io   /*!< Signal name */
#define BOARD_INITPINS_ADC_GROUP_SELECT_1_CHANNEL                            31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ADC_GROUP_SELECT_1_GPIO                             GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_ADC_GROUP_SELECT_1_GPIO_PIN                           31U   /*!< GPIO pin number */
#define BOARD_INITPINS_ADC_GROUP_SELECT_1_GPIO_PIN_MASK              (1U << 31U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_ADC_GROUP_SELECT_1_PORT                             GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_ADC_GROUP_SELECT_1_PIN                                31U   /*!< PORT pin number */
#define BOARD_INITPINS_ADC_GROUP_SELECT_1_PIN_MASK                   (1U << 31U)   /*!< PORT pin mask */

/* GPIO_B0_00 (coord D7), MCU_LED_CELL_CTRL1 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_CELL_CTRL1_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LED_CELL_CTRL1_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_CELL_CTRL1_CHANNEL                                 0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_CELL_CTRL1_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_CELL_CTRL1_GPIO_PIN                                0U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_CELL_CTRL1_GPIO_PIN_MASK                   (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_CELL_CTRL1_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_CELL_CTRL1_PIN                                     0U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_CELL_CTRL1_PIN_MASK                        (1U << 0U)   /*!< PORT pin mask */

/* GPIO_B0_01 (coord E7), MCU_LED_CELL_CTRL2 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_CELL_CTRL2_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LED_CELL_CTRL2_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_CELL_CTRL2_CHANNEL                                 1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_CELL_CTRL2_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_CELL_CTRL2_GPIO_PIN                                1U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_CELL_CTRL2_GPIO_PIN_MASK                   (1U << 1U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_CELL_CTRL2_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_CELL_CTRL2_PIN                                     1U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_CELL_CTRL2_PIN_MASK                        (1U << 1U)   /*!< PORT pin mask */

/* GPIO_B0_02 (coord E8), MCU_LED_CELL_CTRL3 */
/* Routed pin properties */
#define BOARD_INITPINS_LED_CELL_CTRL3_PERIPHERAL                           GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LED_CELL_CTRL3_SIGNAL                             gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_CELL_CTRL3_CHANNEL                                 2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_CELL_CTRL3_GPIO                                 GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_CELL_CTRL3_GPIO_PIN                                2U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_CELL_CTRL3_GPIO_PIN_MASK                   (1U << 2U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_CELL_CTRL3_PORT                                 GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_CELL_CTRL3_PIN                                     2U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_CELL_CTRL3_PIN_MASK                        (1U << 2U)   /*!< PORT pin mask */

/* GPIO_B1_00 (coord A11), MCU_SINK_DAC_0 */
/* Routed pin properties */
#define BOARD_INITPINS_SINK_DAC_0_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SINK_DAC_0_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SINK_DAC_0_CHANNEL                                    16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SINK_DAC_0_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_0_GPIO_PIN                                   16U   /*!< GPIO pin number */
#define BOARD_INITPINS_SINK_DAC_0_GPIO_PIN_MASK                      (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SINK_DAC_0_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_0_PIN                                        16U   /*!< PORT pin number */
#define BOARD_INITPINS_SINK_DAC_0_PIN_MASK                           (1U << 16U)   /*!< PORT pin mask */

/* GPIO_B1_01 (coord B11), MCU_SINK_DAC_1 */
/* Routed pin properties */
#define BOARD_INITPINS_SINK_DAC_1_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SINK_DAC_1_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SINK_DAC_1_CHANNEL                                    17U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SINK_DAC_1_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_1_GPIO_PIN                                   17U   /*!< GPIO pin number */
#define BOARD_INITPINS_SINK_DAC_1_GPIO_PIN_MASK                      (1U << 17U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SINK_DAC_1_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_1_PIN                                        17U   /*!< PORT pin number */
#define BOARD_INITPINS_SINK_DAC_1_PIN_MASK                           (1U << 17U)   /*!< PORT pin mask */

/* GPIO_B1_02 (coord C11), MCU_SINK_DAC_2 */
/* Routed pin properties */
#define BOARD_INITPINS_SINK_DAC_2_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SINK_DAC_2_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SINK_DAC_2_CHANNEL                                    18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SINK_DAC_2_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_2_GPIO_PIN                                   18U   /*!< GPIO pin number */
#define BOARD_INITPINS_SINK_DAC_2_GPIO_PIN_MASK                      (1U << 18U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SINK_DAC_2_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_2_PIN                                        18U   /*!< PORT pin number */
#define BOARD_INITPINS_SINK_DAC_2_PIN_MASK                           (1U << 18U)   /*!< PORT pin mask */

/* GPIO_B1_03 (coord D11), MCU_SINK_DAC_3 */
/* Routed pin properties */
#define BOARD_INITPINS_SINK_DAC_3_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SINK_DAC_3_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SINK_DAC_3_CHANNEL                                    19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SINK_DAC_3_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_3_GPIO_PIN                                   19U   /*!< GPIO pin number */
#define BOARD_INITPINS_SINK_DAC_3_GPIO_PIN_MASK                      (1U << 19U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SINK_DAC_3_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_3_PIN                                        19U   /*!< PORT pin number */
#define BOARD_INITPINS_SINK_DAC_3_PIN_MASK                           (1U << 19U)   /*!< PORT pin mask */

/* GPIO_B1_04 (coord E12), MCU_SINK_DAC_4 */
/* Routed pin properties */
#define BOARD_INITPINS_SINK_DAC_4_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SINK_DAC_4_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SINK_DAC_4_CHANNEL                                    20U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SINK_DAC_4_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_4_GPIO_PIN                                   20U   /*!< GPIO pin number */
#define BOARD_INITPINS_SINK_DAC_4_GPIO_PIN_MASK                      (1U << 20U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SINK_DAC_4_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_4_PIN                                        20U   /*!< PORT pin number */
#define BOARD_INITPINS_SINK_DAC_4_PIN_MASK                           (1U << 20U)   /*!< PORT pin mask */

/* GPIO_B1_05 (coord D12), MCU_SINK_DAC_5 */
/* Routed pin properties */
#define BOARD_INITPINS_SINK_DAC_5_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SINK_DAC_5_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SINK_DAC_5_CHANNEL                                    21U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SINK_DAC_5_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_5_GPIO_PIN                                   21U   /*!< GPIO pin number */
#define BOARD_INITPINS_SINK_DAC_5_GPIO_PIN_MASK                      (1U << 21U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SINK_DAC_5_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_5_PIN                                        21U   /*!< PORT pin number */
#define BOARD_INITPINS_SINK_DAC_5_PIN_MASK                           (1U << 21U)   /*!< PORT pin mask */

/* GPIO_B1_06 (coord C12), MCU_SINK_DAC_6 */
/* Routed pin properties */
#define BOARD_INITPINS_SINK_DAC_6_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SINK_DAC_6_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SINK_DAC_6_CHANNEL                                    22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SINK_DAC_6_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_6_GPIO_PIN                                   22U   /*!< GPIO pin number */
#define BOARD_INITPINS_SINK_DAC_6_GPIO_PIN_MASK                      (1U << 22U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SINK_DAC_6_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_6_PIN                                        22U   /*!< PORT pin number */
#define BOARD_INITPINS_SINK_DAC_6_PIN_MASK                           (1U << 22U)   /*!< PORT pin mask */

/* GPIO_B1_07 (coord B12), MCU_SINK_DAC_7 */
/* Routed pin properties */
#define BOARD_INITPINS_SINK_DAC_7_PERIPHERAL                               GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SINK_DAC_7_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SINK_DAC_7_CHANNEL                                    23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SINK_DAC_7_GPIO                                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_7_GPIO_PIN                                   23U   /*!< GPIO pin number */
#define BOARD_INITPINS_SINK_DAC_7_GPIO_PIN_MASK                      (1U << 23U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SINK_DAC_7_PORT                                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SINK_DAC_7_PIN                                        23U   /*!< PORT pin number */
#define BOARD_INITPINS_SINK_DAC_7_PIN_MASK                           (1U << 23U)   /*!< PORT pin mask */

/* GPIO_B1_08 (coord A12), MCU_LED_CELL_EN */
/* Routed pin properties */
#define BOARD_INITPINS_LED_CELL_EN_PERIPHERAL                              GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LED_CELL_EN_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_CELL_EN_CHANNEL                                   24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_CELL_EN_GPIO                                    GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_CELL_EN_GPIO_PIN                                  24U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_CELL_EN_GPIO_PIN_MASK                     (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_CELL_EN_PORT                                    GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_CELL_EN_PIN                                       24U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_CELL_EN_PIN_MASK                          (1U << 24U)   /*!< PORT pin mask */

/* GPIO_B1_09 (coord A13), MCU_LED_GROUP_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_LED_GROUP_CLK_PERIPHERAL                            GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LED_GROUP_CLK_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_GROUP_CLK_CHANNEL                                 25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GROUP_CLK_GPIO                                  GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GROUP_CLK_GPIO_PIN                                25U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_GROUP_CLK_GPIO_PIN_MASK                   (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_GROUP_CLK_PORT                                  GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GROUP_CLK_PIN                                     25U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_GROUP_CLK_PIN_MASK                        (1U << 25U)   /*!< PORT pin mask */

/* GPIO_B1_10 (coord B13), MCU_LED_GROUP_EN */
/* Routed pin properties */
#define BOARD_INITPINS_LED_GROUP_EN_PERIPHERAL                             GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LED_GROUP_EN_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LED_GROUP_EN_CHANNEL                                  26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_GROUP_EN_GPIO                                   GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GROUP_EN_GPIO_PIN                                 26U   /*!< GPIO pin number */
#define BOARD_INITPINS_LED_GROUP_EN_GPIO_PIN_MASK                    (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LED_GROUP_EN_PORT                                   GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GROUP_EN_PIN                                      26U   /*!< PORT pin number */
#define BOARD_INITPINS_LED_GROUP_EN_PIN_MASK                         (1U << 26U)   /*!< PORT pin mask */

/* GPIO_B1_11 (coord C13), MCU_PD_SHIFT_CLK */
/* Routed pin properties */
#define BOARD_INITPINS_PD_SHIFT_CLK_PERIPHERAL                             GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_PD_SHIFT_CLK_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITPINS_PD_SHIFT_CLK_CHANNEL                                  27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PD_SHIFT_CLK_GPIO                                   GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_PD_SHIFT_CLK_GPIO_PIN                                 27U   /*!< GPIO pin number */
#define BOARD_INITPINS_PD_SHIFT_CLK_GPIO_PIN_MASK                    (1U << 27U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_PD_SHIFT_CLK_PORT                                   GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_PD_SHIFT_CLK_PIN                                      27U   /*!< PORT pin number */
#define BOARD_INITPINS_PD_SHIFT_CLK_PIN_MASK                         (1U << 27U)   /*!< PORT pin mask */

/* GPIO_B1_14 (coord C14), MCU_PD_SHIFT_DATA */
/* Routed pin properties */
#define BOARD_INITPINS_PD_SHIFT_DATA_PERIPHERAL                            GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_PD_SHIFT_DATA_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_PD_SHIFT_DATA_CHANNEL                                 30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PD_SHIFT_DATA_GPIO                                  GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_PD_SHIFT_DATA_GPIO_PIN                                30U   /*!< GPIO pin number */
#define BOARD_INITPINS_PD_SHIFT_DATA_GPIO_PIN_MASK                   (1U << 30U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_PD_SHIFT_DATA_PORT                                  GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_PD_SHIFT_DATA_PIN                                     30U   /*!< PORT pin number */
#define BOARD_INITPINS_PD_SHIFT_DATA_PIN_MASK
#endif
/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */

#endif
void BOARD_InitPins(void);

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_UART1_TXD_PERIPHERAL                        LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_UART1_TXD_SIGNAL                                 TX   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_UART1_RXD_PERIPHERAL                        LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_UART1_RXD_SIGNAL                                 RX   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UART(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSDRAM(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCSI(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLCD(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCAN(void);

/* GPIO_EMC_40 (coord A7), ENET_MDC */
/* Routed pin properties */
#define BOARD_INITENET_ENET_MDC_PERIPHERAL                                  ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_MDC_SIGNAL                                  enet_mdc   /*!< Signal name */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
/* Routed pin properties */
#define BOARD_INITENET_ENET_MDIO_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_MDIO_SIGNAL                                enet_mdio   /*!< Signal name */

/* GPIO_B1_10 (coord B13), MCU_LED_GROUP_EN */
/* Routed pin properties */
#define BOARD_INITENET_ENET_TX_CLK_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_TX_CLK_SIGNAL                           enet_ref_clk   /*!< Signal name */

/* GPIO_B1_04 (coord E12), MCU_SINK_DAC_4 */
/* Routed pin properties */
#define BOARD_INITENET_ENET_RXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_RXD0_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITENET_ENET_RXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_B1_05 (coord D12), MCU_SINK_DAC_5 */
/* Routed pin properties */
#define BOARD_INITENET_ENET_RXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_RXD1_SIGNAL                             enet_rx_data   /*!< Signal name */
#define BOARD_INITENET_ENET_RXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_B1_06 (coord C12), MCU_SINK_DAC_6 */
/* Routed pin properties */
#define BOARD_INITENET_ENET_CRS_DV_PERIPHERAL                               ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_CRS_DV_SIGNAL                             enet_rx_en   /*!< Signal name */

/* GPIO_B1_11 (coord C13), MCU_PD_SHIFT_CLK */
/* Routed pin properties */
#define BOARD_INITENET_ENET_RXER_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_RXER_SIGNAL                               enet_rx_er   /*!< Signal name */

/* GPIO_B1_07 (coord B12), MCU_SINK_DAC_7 */
/* Routed pin properties */
#define BOARD_INITENET_ENET_TXD0_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_TXD0_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITENET_ENET_TXD0_CHANNEL                                      0U   /*!< Signal channel */

/* GPIO_B1_08 (coord A12), MCU_LED_CELL_EN */
/* Routed pin properties */
#define BOARD_INITENET_ENET_TXD1_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_TXD1_SIGNAL                             enet_tx_data   /*!< Signal name */
#define BOARD_INITENET_ENET_TXD1_CHANNEL                                      1U   /*!< Signal channel */

/* GPIO_B1_09 (coord A13), MCU_LED_GROUP_CLK */
/* Routed pin properties */
#define BOARD_INITENET_ENET_TXEN_PERIPHERAL                                 ENET   /*!< Peripheral name */
#define BOARD_INITENET_ENET_TXEN_SIGNAL                               enet_tx_en   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENET(void);

/* GPIO_SD_B0_05 (coord J2), SD1_D3 */
/* Routed pin properties */
#define BOARD_INITUSDHC_SD1_D3_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHC_SD1_D3_SIGNAL                                 usdhc_data   /*!< Signal name */
#define BOARD_INITUSDHC_SD1_D3_CHANNEL                                        3U   /*!< Signal channel */

/* GPIO_SD_B0_04 (coord H2), SD1_D2 */
/* Routed pin properties */
#define BOARD_INITUSDHC_SD1_D2_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHC_SD1_D2_SIGNAL                                 usdhc_data   /*!< Signal name */
#define BOARD_INITUSDHC_SD1_D2_CHANNEL                                        2U   /*!< Signal channel */

/* GPIO_SD_B0_03 (coord K1), SD1_D1/J24[5]/SPI_MISO */
/* Routed pin properties */
#define BOARD_INITUSDHC_SD1_D1_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHC_SD1_D1_SIGNAL                                 usdhc_data   /*!< Signal name */
#define BOARD_INITUSDHC_SD1_D1_CHANNEL                                        1U   /*!< Signal channel */

/* GPIO_SD_B0_02 (coord J1), SD1_D0/J24[4]/SPI_MOSI/PWM */
/* Routed pin properties */
#define BOARD_INITUSDHC_SD1_D0_PERIPHERAL                                 USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHC_SD1_D0_SIGNAL                                 usdhc_data   /*!< Signal name */
#define BOARD_INITUSDHC_SD1_D0_CHANNEL                                        0U   /*!< Signal channel */

/* GPIO_SD_B0_00 (coord J4), SD1_CMD/J24[6] */
/* Routed pin properties */
#define BOARD_INITUSDHC_SD1_CMD_PERIPHERAL                                USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHC_SD1_CMD_SIGNAL                                 usdhc_cmd   /*!< Signal name */

/* GPIO_SD_B0_01 (coord J3), SD1_CLK/J24[3] */
/* Routed pin properties */
#define BOARD_INITUSDHC_SD1_CLK_PERIPHERAL                                USDHC1   /*!< Peripheral name */
#define BOARD_INITUSDHC_SD1_CLK_SIGNAL                                 usdhc_clk   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSDHC(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitHyperFlash(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
